config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

    root 'static_pages#home'
    get  '/help',    to: 'static_pages#help'
    get  '/about',   to: 'static_pages#about'
    get  '/contact', to: 'static_pages#contact'
    get '/signup',  to: 'users#new'
    post '/signup', to: 'users#create'
    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy'
    resources :users do
      member do
        get :following, :followers, :likes
      end
    end
    get '/search', to: 'users#search'
    get '/protein', to: 'users#protein'
    get '/wear', to: 'users#wear'
    get '/training_items', to: 'users#training_items'
    get '/others', to: 'users#others'
    resources :account_activations, only: [:edit]
    resources :password_resets, only: [:new, :create, :edit, :update]
    resources :microposts,          only: [:new, :create, :destroy]
    resources :relationships,       only: [:create, :destroy]
    
  #like機能拡張用に指定
  resources :likes, only: [:create, :destroy]
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # edit、updateアクションが実行される前に実行されるフィルター
  before_action :logged_in_user, only:[:edit, :update, :index, :destroy,
                                  :following, :followers, :likes, :protein, :wear,
                                    :training_items, :others]
  before_action :correct_user, only:[:edit, :update]
  before_action :admin_user, only: :destroy
  
  def index
    # class名: User::ActiveRecord_Relation 
    @users = User.where(activated: true).paginate(page: params[:page])
  end
  
  def show
    # /users/:idから値を取得して@userに代入
    @user = User.find(params[:id])
    # class名: Micropost::ActiveRecord_AssociationRelation 
    @microposts = @user.microposts.paginate(page: params[:page])
    # ユーザーが有効化されていない場合はルートURLにリダイレクトさせる
    redirect_to root_url and return unless @user.activated?
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      # 保存に成功した時の処理
      @user.send_activation_email
      flash[:info] = "Please check your email to activate your account."
      redirect_to root_url
    else
      render 'new'
    end
  end
  
  def edit
    # /users/:id/editから値を取得して@userに代入
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      # 更新に成功した場合の処理
      flash[:success] = "Profile updated!"
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end
  
  def following
    @title = "フォロー中"
    @user  = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'show_following'
  end

  def followers
    @title = "フォロワー"
    @user  = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_followers'
  end
  
  def search
    @microposts = Micropost.all.paginate(page: params[:page]).search(params[:search])
    @user = current_user
    @title = "検索結果"
    render 'search_posts'
  end
  
  def likes
    @user = User.find(params[:id])
    @likes = Like.where(user_id: @user.id)
    # クラス名: Array(ただの配列だからモデルにあるsearchメソッドが使えない)
    # Arrayクラスに対してMicropostクラスメソッドは使えない
    @microposts = @likes.map do |like|
      like.micropost
    end
    render 'show_likes'
  end
  
  def protein
    @title = "#プロテイン"
    @category = "#プロテイン"
    # @category_url = "/protein"
    @user = current_user
    @microposts = Micropost.paginate(page: params[:page]).where(category: "protein")
    render 'category_posts'
  end
  
  def wear
    @title = "#ウェア"
    @category = "#ウェア"
    # @category_url = "/wear"
    @user = current_user
    @microposts = Micropost.paginate(page: params[:page]).where(category: "wear")
    render 'category_posts'
  end
  
  def training_items
    @title = "#トレーニング用品"
    @category = "#トレーニング用品"
    # @category_url = "/training_items"
    @user = current_user
    @microposts = Micropost.paginate(page: params[:page]).where(category: "training_items")
    render 'category_posts'
  end
  
  def others
    @title = "#その他"
    @category = "#その他"
    # @category_url = "/others"
    @user = current_user
    @microposts = Micropost.paginate(page: params[:page]).where(category: "others")
    render 'category_posts'
  end
  
  private
  
    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation, :profile, :picture)
    end
    
    # beforeアクション
    
    # 正しいユーザーかどうか確認
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
    
    # 管理者かどうか確認
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
  
end

app/helpers/users_helper.rb
module UsersHelper
  
  def avatar_for(user, options = { size: "50x50" })
    size = options[:size]
    if user.picture.present?
      image_tag(user.picture.url, alt: user.name, :size => size, class: "user-image")
    else
      image_tag("default.jpg", alt: user.name, :size => size, class: "user-image")
    end
  end
  
end

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "フォローする", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user, url: yield(:url)) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name, "ユーザー名(※必須)" %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email, "メールアドレス(※必須)" %>
      <%= f.email_field :email, class: 'form-control' %>
      
      <%= f.label :profile, "自己紹介文" %>
      <%= f.text_area :profile,  class: 'form-control', placeholder: "160文字以内で入力してください" %>
      
      <%= f.label :picture, "プロフィール画像" %>
      <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
      
      <%= f.label :password, "パスワード(※必須)" %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "パスワードの再入力(※必須)" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit yield(:botton_text), class: "btn btn-primary" %>
<% end %>

<script type="text/javascript">
  $('#user_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "フォローを解除", class: "btn btn-default" %>
<% end %>

<!--/relationship/id/destroy-->
<!--名前付きルート relationship_path(id)-->

app/views/users/_user.html.erb
<li>
  <%= avatar_for user, size: "50x50" %>
  <%= link_to user.name, user %>
  <!--current_userがadminかつcurrent_userとuserの値が一致しない場合-->
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
  <p><%= user.profile %></p> 
</li>

app/views/users/category_posts.html.erb
<% provide(:title, @title) %>
<% provide(:category, @category) %>
<%= render 'users/category' %>

app/views/users/category_protein.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <% if current_user?(@user) %>
      <%= link_to "変更", edit_user_path(current_user)%>
      <% end %>
      <p style="margin-bottom: 15px;"><%= @user.profile %></p>
      <section class="stats">
        <%= render 'shared/stats' %>
      </section>
    </aside>
    <div class="col-md-8">
      <div>
      <h3 style="float: left;">#プロテイン</h3>
      
      <!--検索機能-->
      
      <div class="search-group" style="float: right; margin-top: 12px;">
      <%= form_tag(root_path, :method => 'get' ) do %>
        <input type="search" name="search" id="search" placeholder="キーワード"><input type="submit" name="" value="検索">
      <% end %>
      </div>
      </div>
      
      <!--検索機能ここまで-->
      
      <ol class="microposts" id="posts" style="clear: both;">
        <% @microposts.each do |micropost| %>
        <li id="micropost-<%= micropost.id %>">
        <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
        <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
        <span class="title">
        <p>商品名: <%= micropost.title %></p>
        <%= link_to "##{micropost.category}", "/#{micropost.category}" %>
        </span>
        <span class="content">
          <%= image_tag micropost.picture.url if micropost.picture? %>
          <%= simple_format(micropost.content) %>
        </span>
        <span class="timestamp">
          Posted <%= time_ago_in_words(micropost.created_at) %> ago.
          <% if current_user?(micropost.user) %>
            <%= link_to "delete", micropost, method: :delete,
                                             data: { confirm: "You sure?" } %>
          <% end %>
        </span>
        <!--like拡張機能-->
        <%= render "likes/like", micropost: micropost %> <!-- Likeビューをパーシャル化する際にMicropostをビューに渡す -->　
        </li>
        <% end %>
      </ol>
  </div>
    </div>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<% provide(:botton_text, "Save Changes") %>
<% provide(:url, user_path) %>
<h1>ユーザー情報の変更</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: yield(:url)) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :ユーザー名 %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :メールアドレス %>
      <%= f.email_field :email, class: 'form-control' %>
      
      <%= f.label :自己紹介文 %>
      <%= f.text_area :profile,  class: 'form-control', placeholder: "160文字以内で入力してください" %>
      
      <%= f.label :プロフィール画像 %>
        <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
      
      <%= f.submit yield(:botton_text), class: "btn btn-primary" %>
      <% end %>
      
      <script type="text/javascript">
      $('#user_picture').bind('change', function() {
      var size_in_megabytes = this.files[0].size/1024/1024;
      if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
        }
        });
      </script>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:search_name, users_path) %>
<% provide(:title, 'ユーザー一覧') %>
<h1>ユーザー一覧</h1>

<%= will_paginate %>

<ul class="users">
  <!--Railsは@usersをUserオブジェクトのリストであると推測する-->
    <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:botton_text, 'Create my account') %>
<% provide(:url, signup_path) %>
<h1>新規登録</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/search_posts.html.erb
<% provide(:title, @title) %>
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <% if current_user?(@user) %>
      <%= link_to "変更", edit_user_path(current_user)%>
      <% end %>
      <p style="margin-bottom: 15px;"><%= @user.profile %></p>
      <section class="stats">
        <%= render 'shared/stats' %>
      </section>
    </aside>
    <div class="col-md-8">
      <div>
      <h3>検索結果</h3>
      <ol class="microposts" id="posts">
        <%= render @microposts %>
      </ol>
      <%= will_paginate @microposts %>
  </div>
    </div>
<% end %>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= avatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
    <% if current_user?(@user) %>
    <%= link_to "変更", edit_user_path(current_user)%>
    <% end %>
    <p style="margin-bottom: 15px;"><%= @user.profile %></p>
    <section class="stats">
      <%= render 'shared/stats' %>
    </section>
    <section class="follow_form">
      <%= render 'follow_form' if logged_in? %>
    </section>
  </aside>
   <div class="col-md-8">
      <h3>投稿一覧 (<%= @user.microposts.count %>)</h3>
      <div class="user-liked-table">
        <%= link_to "投稿一覧", user_path(@user) %>
        <%= link_to "お気に入り", likes_user_path(@user) %>
      </div>
      <ol class="microposts" id="posts">
        <%= render @microposts %>
      </ol>
      <%= will_paginate @microposts %>
  </div>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= gravatar_for @user %>
      <h1><%= @user.name %></h1>
      <span><%= link_to "view my profile", @user %></span>
      <span><b>Microposts:</b> <%= @user.microposts.count %></span>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
      <% if @users.any? %>
        <div class="user_avatars">
          <% @users.each do |user| %>
            <%= link_to gravatar_for(user, size: 30), user %>
          <% end %>
        </div>
      <% end %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users follow">
        <%= render @users %>
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>
</div>

app/views/users/show_following.html.erb
<% provide(:title, @title) %>
<% provide(:search_name, following_user_path(@user)) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= avatar_for @user %>
      <h1><%= @user.name %></h1>
      <span><%= link_to "プロフィール", @user %></span>
      <span><%= pluralize(current_user.microposts.count, "microposts") %></span>
    </section>
    <% if current_user?(@user) %>
    <%= link_to "変更", edit_user_path(current_user)%>
    <% end %>
    <p style="margin-bottom: 15px;"><%= @user.profile %></p>
    <section class="stats">
      <%= render 'shared/stats' %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users follow">
        <%= render @users %>
      </ul>
      <%= will_paginate %>
    <% end %>
</div>