config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

    root 'static_pages#home'
    get  '/help',    to: 'static_pages#help'
    get  '/about',   to: 'static_pages#about'
    get  '/contact', to: 'static_pages#contact'
    get '/signup',  to: 'users#new'
    post '/signup', to: 'users#create'
    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy'
    resources :users do
      member do
        get :following, :followers, :likes
      end
    end
    get '/search', to: 'users#search'
    get '/protein', to: 'users#protein'
    get '/wear', to: 'users#wear'
    get '/training_items', to: 'users#training_items'
    get '/others', to: 'users#others'
    resources :account_activations, only: [:edit]
    resources :password_resets, only: [:new, :create, :edit, :update]
    resources :microposts,          only: [:new, :create, :destroy]
    resources :relationships,       only: [:create, :destroy]
    
  #like機能拡張用に指定
  resources :likes, only: [:create, :destroy]
end

app/views/layouts/_footer.html.erb
<div id="footerWrap">
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "Home",   root_path %></li>
      <li><%= link_to "Help",   help_path %></li>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
    <p>
    Copyright © Yuki Aida, All Rights Reserved.
    </p>
</footer>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "YourProtein App", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav">
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "About",   about_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Category <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "プロテイン", "/protein" %></li>
              <li><%= link_to "ウェア", "/wear" %></li>
              <li><%= link_to "トレーニング用品", "/training_items" %></li>
              <li><%= link_to "その他", "/others" %></li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
          <li><div class="search-group" style=><%= render 'shared/search' %></div></li>
        <% else %>
          <li><%= link_to "Sign up", signup_path %></li>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <!--<div class="alert alert-<%= message_type %>"><%= message %></div>と同義-->
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <!--開発環境でのみデバッグ情報を表示-->
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>